-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require("wezterm")
local sessionizer = wezterm.plugin.require("https://github.com/mikkasendke/sessionizer.wezterm")
local history = wezterm.plugin.require("https://github.com/mikkasendke/sessionizer-history")

local schema = {
	options = { callback = history.Wrapper(sessionizer.DefaultCallback) },
	sessionizer.DefaultWorkspace({}),
	history.MostRecentWorkspace({}),

	wezterm.home_dir .. "/repos",

	sessionizer.FdSearch(wezterm.home_dir .. "/repos"),

	processing = sessionizer.for_each_entry(function(entry)
		entry.label = entry.label:gsub(wezterm.home_dir, "~")
	end),
}

wezterm.on("update-right-status", function(window, pane)
	window:set_right_status(window:active_workspace())
end)

return {
	color_scheme = "Noctalia",
	enable_wayland = false,
	enable_tab_bar = false,
	font = wezterm.font("iosevka nerd font", { weight = "Bold", stretch = "Normal", style = "Normal" }),
	leader = { key = "Space", mods = "CTRL", timeout_milliseconds = 1000 },
	keys = {
		{
			key = "u",
			mods = "LEADER",
			action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }),
		},
		{
			key = "i",
			mods = "LEADER",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
		{
			key = "c",
			mods = "LEADER",
			action = wezterm.action.SpawnTab("CurrentPaneDomain"),
		},
		{
			key = "p",
			mods = "LEADER",
			action = wezterm.action.MoveTabRelative(-1),
		},
		{
			key = "n",
			mods = "LEADER",
			action = wezterm.action.MoveTabRelative(1),
		},
		{
			key = "x",
			mods = "LEADER",
			action = wezterm.action.CloseCurrentPane({ confirm = true }),
		},
		{
			key = "h",
			mods = "CTRL",
			action = wezterm.action.ActivatePaneDirection("Left"),
		},
		{
			key = "j",
			mods = "CTRL",
			action = wezterm.action.ActivatePaneDirection("Down"),
		},
		{
			key = "k",
			mods = "CTRL",
			action = wezterm.action.ActivatePaneDirection("Up"),
		},
		{
			key = "l",
			mods = "CTRL",
			action = wezterm.action.ActivatePaneDirection("Right"),
		},
		{
			key = "r",
			mods = "LEADER",
			action = sessionizer.show(schema),
		},
	},

	inactive_pane_hsb = {
		saturation = 0.74,
		brightness = 0.4,
	},

	window_background_opacity = 0,
}
